// Données d'interprétation pour les 9 types de l'Ennéagramme
var ENNEAGRAMME_TYPES = {
  1: {
    name: "Le Perfectionniste",
    tagline: "Principé, orienté vers l'amélioration",
    emoji: "⚖️",
    color: "#f59e0b",
    coreMotivation: "Être bon, vertueux, intègre et en accord avec ses valeurs.",
    coreFear: "Être mauvais, corrompu ou défectueux.",
    description: "Les type 1 sont des réformateurs animés par un sens aigu du bien et du mal. Ils ont une voix intérieure critique qui les pousse continuellement à s'améliorer et à améliorer le monde. Leur rigueur morale et leur sens du devoir sont remarquables, même s'ils peuvent parfois mener à un perfectionnisme épuisant.",
    strengths: ["Intégrité et éthique solides", "Organisation et méthode", "Persévérance et autodiscipline", "Sens de la justice", "Fiabilité et responsabilité", "Attention aux détails"],
    weaknesses: ["Perfectionnisme paralysant", "Critique excessive de soi et des autres", "Rigidité et manque de flexibilité", "Colère refoulée", "Difficulté à se détendre et à jouer"],
    cognitiveStyle: "Analyse rigoureuse selon des critères moraux et éthiques clairs. Pense en termes de ce qui est «juste» vs «incorrect».",
    relationalStyle: "Relations fondées sur des valeurs partagées et la fiabilité. Peut être exigeant(e) envers les autres comme envers soi-même.",
    professionalStyle: "Excelle dans les rôles qui demandent précision, éthique et amélioration continue. Idéal pour le contrôle qualité, le droit, la médecine.",
    wings: { left: 9, right: 2 },
    growth: "Vers le type 7 : apprendre à se détendre, à apprécier l'imperfection et à trouver la joie.",
    stress: "Vers le type 4 : devenir mélancolique, dramatique et se sentir incompris(e)."
  },
  2: {
    name: "L'Assistant",
    tagline: "Généreux, attentionné, altruiste",
    emoji: "🤝",
    color: "#ec4899",
    coreMotivation: "Être aimé(e), apprécié(e) et nécessaire aux autres.",
    coreFear: "Être indésirable, inutile ou sans amour.",
    description: "Les type 2 sont des aides naturelles, toujours prêtes à donner d'elles-mêmes pour les autres. Empathiques et intuitifs face aux besoins d'autrui, ils ont souvent du mal à reconnaître et exprimer leurs propres besoins. Leur générosité est immense, mais peut cacher un besoin profond de reconnaissance.",
    strengths: ["Générosité et altruisme sincères", "Empathie intuitive", "Chaleur humaine", "Capacité à soutenir les autres", "Créativité dans l'aide", "Loyauté profonde"],
    weaknesses: ["Difficulté à exprimer ses propres besoins", "Tendance à la manipulation douce", "Sentiment d'être sous-estimé(e)", "Orgueil masqué", "Dépendance à l'approbation des autres"],
    cognitiveStyle: "Orienté vers les besoins des autres. Perçoit intuitivement les états émotionnels et les besoins non exprimés.",
    relationalStyle: "Chaleureux et nourricier. Investit profondément dans ses relations. Parfois envahissant par excès de soin.",
    professionalStyle: "Excelle dans les métiers d'aide, de soin et d'enseignement. A besoin de se sentir utile et apprécié.",
    wings: { left: 1, right: 3 },
    growth: "Vers le type 4 : apprendre à se connecter à ses propres émotions authentiques.",
    stress: "Vers le type 8 : devenir contrôlant(e) et agressif(ve) quand on se sent rejeté(e)."
  },
  3: {
    name: "Le Battant",
    tagline: "Ambitieux, performant, adaptable",
    emoji: "🏆",
    color: "#f97316",
    coreMotivation: "Être valorisé(e), reconnu(e) et admiré(e) pour ses succès.",
    coreFear: "Être sans valeur, un échec ou être perçu(e) comme incompétent(e).",
    description: "Les type 3 sont des réalisateurs nés, animés par le désir de réussir et d'être reconnus. Adaptables et efficaces, ils savent se transformer pour répondre aux attentes de leur environnement. Leur énergie et leur capacité à atteindre des objectifs sont impressionnantes, mais ils peuvent parfois perdre contact avec leur vrai moi.",
    strengths: ["Ambition et énergie", "Adaptabilité remarquable", "Efficacité et productivité", "Leadership naturel", "Charisme et persuasion", "Orientation résultats"],
    weaknesses: ["Image avant authenticité", "Compétitivité excessive", "Difficulté à se montrer vulnérable", "Workaholisme", "Peut manipuler pour réussir"],
    cognitiveStyle: "Pense en termes d'objectifs, de stratégies et de résultats. Évalue constamment l'efficacité de ses actions.",
    relationalStyle: "Charismatique et attrayant socialement. Peut traiter les relations comme des outils de succès. Profondément loyal quand la confiance est établie.",
    professionalStyle: "Excelle dans les environnements compétitifs. Ventes, management, entrepreneuriat, spectacle.",
    wings: { left: 2, right: 4 },
    growth: "Vers le type 6 : développer l'authenticité, la loyauté et l'engagement envers les autres.",
    stress: "Vers le type 9 : se désengager, perdre sa motivation et éviter les conflits."
  },
  4: {
    name: "L'Individualiste",
    tagline: "Créatif, profond, authentique",
    emoji: "🎨",
    color: "#8b5cf6",
    coreMotivation: "Être soi-même, exprimer son unicité et sa profondeur émotionnelle.",
    coreFear: "N'avoir aucune identité propre, être insignifiant(e) ou ordinaire.",
    description: "Les type 4 sont des créatifs dotés d'une vie intérieure très riche et d'une sensibilité émotionnelle profonde. Ils cherchent l'authenticité absolue et rejettent tout ce qui est superficiel. Leur conscience de leur propre différence peut les rendre mélancoliques, mais aussi profondément créatifs et empathiques.",
    strengths: ["Créativité et expression artistique", "Profondeur émotionnelle", "Authenticité et originalité", "Empathie profonde pour la souffrance", "Sens esthétique développé", "Introspection riche"],
    weaknesses: ["Mélancolie et repli sur soi", "Envie des autres", "Sentiment de manque persistant", "Humeurs changeantes", "Peut sembler dramatique ou égotique"],
    cognitiveStyle: "Très introspectif. Traite l'expérience à travers un filtre émotionnel intense. Cherche le sens profond dans tout.",
    relationalStyle: "Recherche des relations intenses et authentiques. Peut idéaliser puis dévaloriser. Profondément loyal dans les relations authentiques.",
    professionalStyle: "Excelle dans les arts, l'écriture, la psychologie, tout ce qui demande profondeur et expression personnelle.",
    wings: { left: 3, right: 5 },
    growth: "Vers le type 1 : développer la discipline, l'action concrète et l'objectivité.",
    stress: "Vers le type 2 : devenir clinquant(e), intrusif(ve) et chercher l'approbation."
  },
  5: {
    name: "L'Observateur",
    tagline: "Analytique, indépendant, expert",
    emoji: "🔬",
    color: "#06b6d4",
    coreMotivation: "Comprendre le monde, accumuler le savoir et préserver son autonomie.",
    coreFear: "Être incompétent(e), ignorant(e) ou envahi(e) par les autres.",
    description: "Les type 5 sont des observateurs perspicaces et des chercheurs infatigables. Ils accumulent le savoir comme une ressource précieuse et ont besoin de comprendre avant d'agir. Leur monde intérieur est riche mais ils ont tendance à se retirer du monde émotionnel et social pour préserver leur énergie.",
    strengths: ["Analyse profonde et rigoureuse", "Expertise dans leurs domaines", "Indépendance d'esprit", "Objectivité", "Originalité de pensée", "Persévérance intellectuelle"],
    weaknesses: ["Isolement social excessif", "Détachement émotionnel", "Avarice des ressources et du temps", "Paralysie analytique", "Difficulté à passer à l'action"],
    cognitiveStyle: "Analytique et systémique. Observe avant d'agir. Cherche à tout comprendre avant de s'engager.",
    relationalStyle: "Peu nombreuses mais profondes. A besoin d'espace et d'indépendance. Très loyal envers ses proches.",
    professionalStyle: "Excelle dans la recherche, la technologie, la philosophie, tout ce qui demande expertise et réflexion.",
    wings: { left: 4, right: 6 },
    growth: "Vers le type 8 : développer la confiance en soi, l'action et le leadership.",
    stress: "Vers le type 7 : devenir distrait(e), dispersé(e) et fuir dans les plaisirs."
  },
  6: {
    name: "Le Loyaliste",
    tagline: "Loyal, vigilant, communautaire",
    emoji: "🛡️",
    color: "#3b82f6",
    coreMotivation: "Être en sécurité, soutenu(e) et guidé(e). Avoir une structure fiable.",
    coreFear: "Être sans soutien, abandonné(e) ou se retrouver dans le danger.",
    description: "Les type 6 sont les plus communs de l'Ennéagramme. Loyaux, responsables et très attentifs aux risques, ils cherchent constamment des systèmes fiables et des personnes de confiance. Leur anticipation des problèmes peut être un atout immense même si elle les rend parfois anxieux.",
    strengths: ["Loyauté et fiabilité absolues", "Anticipation des risques", "Esprit d'équipe fort", "Courage face au danger", "Sens des responsabilités", "Solidarité et soutien"],
    weaknesses: ["Anxiété et doute de soi", "Tendance à tester les relations", "Autorité ambivalente", "Scepticisme excessif", "Procrastination par peur de se tromper"],
    cognitiveStyle: "Pensée orientée vers la sécurité et la prévention des risques. Excellente anticipation des problèmes.",
    relationalStyle: "Très loyal envers les personnes et les groupes de confiance. Tests de loyauté fréquents.",
    professionalStyle: "Excelle dans les rôles qui demandent fiabilité, analyse des risques et travail d'équipe.",
    wings: { left: 5, right: 7 },
    growth: "Vers le type 9 : développer la paix intérieure et la confiance en la vie.",
    stress: "Vers le type 3 : devenir compétitif(ve) et orienté(e) image pour compenser l'insécurité."
  },
  7: {
    name: "L'Épicurien",
    tagline: "Enthousiaste, aventurier, optimiste",
    emoji: "✨",
    color: "#10b981",
    coreMotivation: "Être comblé(e) et heureux(se). Vivre des expériences stimulantes et variées.",
    coreFear: "Être privé(e), souffrir ou rater quelque chose d'important.",
    description: "Les type 7 sont des esprits enthousiastes qui cherchent sans cesse de nouvelles aventures et expériences. Leur optimisme naturel et leur énergie communicative sont inspirants. Ils ont souvent de nombreux projets en parallèle et ont du mal à s'engager sur une seule voie, craignant de manquer autre chose.",
    strengths: ["Enthousiasme et joie de vivre", "Optimisme contagieux", "Créativité et polyvalence", "Adaptabilité rapide", "Esprit d'initiative", "Capacité à inspirer"],
    weaknesses: ["Difficulté à s'engager durablement", "Fuite des émotions difficiles", "Dispersion et impatience", "Superficialité possible", "Manque de profondeur dans les engagements"],
    cognitiveStyle: "Pensée rapide, associative et créative. Saute d'une idée à l'autre. Très doué pour la synthèse et les connexions.",
    relationalStyle: "Nombreuses relations joyeuses et légères. Peut avoir du mal à s'engager en profondeur.",
    professionalStyle: "Excelle dans les environnements dynamiques, créatifs, le marketing, l'entrepreneuriat.",
    wings: { left: 6, right: 8 },
    growth: "Vers le type 5 : développer la profondeur, la concentration et la persévérance.",
    stress: "Vers le type 1 : devenir critique, rigide et perfectionniste quand sous pression."
  },
  8: {
    name: "Le Chef",
    tagline: "Puissant, protecteur, décisif",
    emoji: "🦁",
    color: "#dc2626",
    coreMotivation: "Se protéger soi-même et ses proches. Avoir le contrôle et ne jamais être contrôlé(e).",
    coreFear: "Être blessé(e), contrôlé(e) ou humilié(e) par les autres.",
    description: "Les type 8 sont des leaders naturels dotés d'une énergie et d'une volonté puissantes. Ils défendent vigoureusement ceux qu'ils aiment et n'hésitent pas à confronter les injustices. Derrière leur force imposante se cache souvent un cœur tendre qu'ils protègent farouchement.",
    strengths: ["Leadership naturel et décisif", "Protection des autres", "Courage et franchise", "Énergie et détermination", "Résistance à l'adversité", "Sens de la justice"],
    weaknesses: ["Contrôle excessif", "Difficulté à montrer sa vulnérabilité", "Intimidation inconsciente", "Tendance à dominer", "Colère explosive"],
    cognitiveStyle: "Pensée directe, pragmatique et orientée vers le pouvoir et le contrôle. Voit clairement qui est avec qui.",
    relationalStyle: "Intensément loyal envers ses proches. Relations franches et directes. Teste la force des autres.",
    professionalStyle: "Excelle dans tout rôle de leadership, entrepreneuriat, politique, tout ce qui demande décision et courage.",
    wings: { left: 7, right: 9 },
    growth: "Vers le type 2 : développer l'empathie, la générosité et l'ouverture à la vulnérabilité.",
    stress: "Vers le type 5 : se retirer, devenir secret et paranoïaque."
  },
  9: {
    name: "Le Médiateur",
    tagline: "Pacifiste, accueillant, stabilisateur",
    emoji: "☮️",
    color: "#64748b",
    coreMotivation: "Avoir la paix intérieure et extérieure. Maintenir l'harmonie et éviter les conflits.",
    coreFear: "La séparation et les conflits. Perdre sa connexion aux autres.",
    description: "Les type 9 sont des médiateurs naturels qui voient plusieurs côtés de chaque situation et cherchent à créer l'harmonie. Leur capacité à comprendre différentes perspectives en fait d'excellents médiateurs. Ils ont souvent du mal à s'affirmer et peuvent s'oublier pour préserver la paix.",
    strengths: ["Sens de l'harmonie et de la paix", "Ouverture d'esprit exceptionnelle", "Patience et tolérance", "Capacité de médiation", "Acceptation et bienveillance", "Stabilité émotionnelle"],
    weaknesses: ["Difficulté à s'affirmer", "Procrastination et inertie", "Évitement des conflits nécessaires", "Tendance à s'effacer", "Difficulté à prioriser ses propres besoins"],
    cognitiveStyle: "Pensée inclusive et non conflictuelle. Voit facilement plusieurs perspectives. A du mal à prioriser.",
    relationalStyle: "Très accueillant et non jugeant. Peut avoir du mal à exprimer ses propres désirs et besoins.",
    professionalStyle: "Excelle dans la médiation, le conseil, les ressources humaines, tout ce qui demande écoute et harmonie.",
    wings: { left: 8, right: 1 },
    growth: "Vers le type 3 : développer l'action, l'ambition et la conscience de sa valeur.",
    stress: "Vers le type 6 : devenir anxieux(se), soupçonneux(se) et chercher des appuis."
  }
};

/**
 * @param {number} type  1-9
 * @returns {Object|null}
 */
function getEnneagrammeInterpretation(type) {
  return ENNEAGRAMME_TYPES[type] || null;
}
